-- Generated by hyprmoncfg

hl.monitor({
  output = "desc:Samsung Display Corp. 0x41AA",
  mode = "2880x1800@120.00",
  position = "4092x1440",
  scale = 1.5,
  sdr_min_luminance = 0.2,
  sdr_max_luminance = 80,
})

hl.monitor({
  output = "desc:ViewSonic Corporation VX3276-QHD V9W205342201",
  mode = "2560x1440@59.95",
  position = "4974x0",
  scale = 1,
  sdr_min_luminance = 0.2,
  sdr_max_luminance = 80,
})

hl.monitor({
  output = "desc:ViewSonic Corporation VX3276-QHD V9W213040176",
  mode = "2560x1440@59.95",
  position = "2374x0",
  scale = 1,
  sdr_min_luminance = 0.2,
  sdr_max_luminance = 80,
})

hl.workspace_rule({ workspace = "1", monitor = "desc:Samsung Display Corp. 0x41AA", default = true })
